---
title:       "Estimation, Confidence Intervals, and Bootstrapping"
subtitle:    "My Personal Notes"
author:      "Max Hachemeister"
date:        last-modified
date-format: iso
format:
  gfm:
    toc:     true
---

# Prerequisites

```{r}
#| label: setup
#| results: false

library(tidyverse)
library(moderndive)
library(infer)
theme_set(theme_light())
```

## Tying the Sampling Distribution to Estimation

#### LC8.1

> What is the expected value of the sample mean weight of almonds in a
> large sample according to the sampling distribution theory?

  * A. It is always larger than the population mean.
  * B. It is always smaller than the population mean.
  * C. It is exactly equal to the population mean.
  * *D. It is equal to the population mean on average but may vary*
       *in a single sample.*
       
#### LC8.2

> What is a *point estimate* and how does it doffer from an *interval*
> *estimate* in the context of statistical estimation?

  * A. A point estimate uses multiple values to estimate a parameter;
       an interval estimate uses a single value.
       
  * *B. A point estimate is a single value used to estimate a parameter;*
       *an interval estimate provides a range of values within which the*
       *parameter likely fails.*
       
  * C. A point estimate is the mean of multiple samples; an interval
       estimate is the median.
       
  * D. A point estimate and an interval estimate are the same and can
       be used interchangeably.
       
##### !error

8.1.2
within 2 standard deviations *form* the mean is 95.45%


#### LC8.3

> What does the population mean ($\mu$) represend in the context of the
> almond activity?

  * A. The average weight of 100 randomly sampled almonds.
  * B. The weight of the heaviest almond in the bowl.
  * *C. The average weight of all 5,000 almonds in the bowl.*
  * D. The total weight of all almonds in the bowl.

#### LC8.4

> Which of the following statements best describes the population
> standard deviation ($\sigma$) in the almond activity?

  * A. It measures the average difference between each almond's
       weight and the sample mean weight.
       
  * *B. It measures the average difference between each almond's*
       *weight and the population mean weight.*
  
  * C. It is equal to the square root of the sample variance.
  
  * D. It is always smaller than the population mean.
  
#### LC8.4

> Why do we use the sample mean to estimate the population mean in the
> almond activity?

  * A. Because the sample mean is always larger than the population mean.
  
  * *B. Because the sample mean is a good estimator of the population*
        *mean due to its unbiasedness.*
       
  * C. Because the sample mean requires less computational effort than
       the population mean.
       
  * D. Because the sample mean eliminates all sampling variation.
  

#### LC8.6

> How is the standard error of the sample mean weight of almonds
> calculated on the context of this example?

  * A. By dividing the sample mean by the population
       standard deviation.
  
  * *B. By dividing the population standard deviation by the*
       *square root of the sample size.*
       
  * C. By multiplying the sample mean by the square root of the
       sample size.
       
  * D. By dividing the population mean by the sample size.

#### LC8.7

> What does a 95% confidence interval represent in the context of the
> almond weight estimation?

  * A. There is a 95% chance that the sample mean is within 1.96
       standard deviations from the population mean.
       
  * B. The intervall will contain 95% of the almond weight from the
       sample.
       
  * *C. There is a 95% chance that the population mean falls within 1.96*
       *standard errors from the sample mean.*
       
  * D. The sample mean is exactly equal to the population mean 95% of the
       time.
       
## PU 8.1.4